### ISSUE TITLE
firefox_target_manifest_dir points to wrong location on Fedora 64bit

### ISSUE THREAD

**Issue by insecure** [rosmanov/chrome-bee#1]
I'm running on Fedora Linux 64 bit. The manifest is copied to the wrong location (`/usr/lib/mozilla/native-messaging-hosts/com.ruslan_osmanov.bee.json`). Bee does not work until I copy that file to `/usr/lib64/mozilla/native-messaging-hosts/com.ruslan_osmanov.bee.json`.
Unfortunately I have not figured out yet how to find out the proper directory automatically. On my machines both directories (`/usr/lib/mozilla` and `/usr/lib64/mozilla`) exist.
Maybe we can assume that it is always `/usr/lib64/mozilla` when running on Fedora 64 bit, e.g. by looking at `/etc/os-release` and `uname -m`?

**Comment by rosmanov** [comment]
I've added some checks including `uname -m`.

Thanks.

**Comment by insecure** [comment]
These changes work for me. Thanks!
