### ISSUE TITLE
not valid syntax to check python version

### ISSUE THREAD

**Issue by dyno** [rosmanov/chrome-bee#2]
https://github.com/rosmanov/chrome-bee/blob/c6cdcad97f99e6e7efd04e07dba7f4ad97d5ba9c/host/install.sh#L30

```
Saved cache into /Users/dynofu/gitroot/chrome-bee/host/vars.cache.sh
  File "<string>", line 1
    import sys; print sys.version_info.major
                        ^
SyntaxError: invalid syntax
```

**Comment by rosmanov** [comment]
@dyno Thanks =)

By the way, there will be a C version of the host, and it will be decoupled from the client. I'll publish the new edition when I have some free time.
