### ISSUE TITLE
Missing Architecture field in the deb

### ISSUE THREAD

**Issue by Pikrass** [rosmanov/chrome-bee#7]
The mandatory 'Architecture' field is not filled in debian/control. This results in a flood of warnings every time I do anything with dpkg (eg installing or upgrading any package):

```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 2615 package 'beectl':
 missing 'Architecture' field
```

I get this additional warning when installing (which needs `--force-architecture` because of this bug):
```
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 9 package 'beectl':
 empty value for 'Architecture' field
```

**Comment by rosmanov** [comment]
Fixed in https://github.com/rosmanov/bee-host/issues/4
